SET NOCOUNT ON;

/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/
SELECT * from Worker;
go

SET NOCOUNT ON;


SELECT DEPARTMENT.DEPT_NAME, count(WORKER.DEPT_ID) FROM DEPARTMENT, WORKER WHERE WORKER.DEPT_ID = DEPARTMENT.ID GROUP BY DEPARTMENT.DEPT_NAME

/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/
go

SET NOCOUNT ON;


SELECT WORKER.FIRST_NAME, WORKER.LAST_NAME, DESIGNATION.TITLE, TITLE.AFFECTED_FROM FROM WORKER, DESIGNATION, TITLE WHERE WORKER.FIRST_NAME = 'Malik' AND WORKER.LAST_NAME = 'Zain' and TITLE.DESIGNATION_ID = DESIGNATION.ID and TITLE.WORKER_REF_ID = WORKER.WORKER_ID ORDER by TITLE.AFFECTED_FROM DESC
/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/
go

SET NOCOUNT ON;


SELECT DEPARTMENT.DEPT_NAME, sum(WORKER.SALARY) FROM DEPARTMENT, WORKER WHERE WORKER.DEPT_ID = DEPARTMENT.ID AND DEPARTMENT.DEPT_NAME = 'Admin' group by DEPARTMENT.DEPT_NAME
/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/
go

SET NOCOUNT ON;


SELECT WORKER.FIRST_NAME, WORKER.LAST_NAME, WORKER.SALARY, coalesce (DEPARTMENT.DEPT_NAME, 'No Department') FROM WORKER left outer join DEPARTMENT on DEPARTMENT.ID = WORKER.DEPT_ID
/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/
go

SET NOCOUNT ON;

SELECT WORKER.FIRST_NAME, WORKER.LAST_NAME, DATEFROMPARTS(DATEPART(YEAR, (WORKER.JOINING_DATE)), DATEPART(month, (WORKER.JOINING_DATE)), DATEPART(DAY, (WORKER.JOINING_DATE))), DATEDIFF(YEAR, (WORKER.JOINING_DATE), GETDATE() + 1) FROM WORKER
/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/

go

SET NOCOUNT ON;

SELECT WORKER.WORKER_ID, WORKER.FIRST_NAME, WORKER.LAST_NAME, WORKER.JOINING_DATE FROM WORKER WHERE WORKER.DEPT_ID IS NULL
/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/

go

SET NOCOUNT ON;


SELECT DEPARTMENT.DEPT_NAME, MAX(WORKER.SALARY) FROM DEPARTMENT, WORKER WHERE WORKER.DEPT_ID = DEPARTMENT.ID GROUP BY DEPARTMENT.DEPT_NAME
/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/
go

SET NOCOUNT ON;


SELECT WORKER.FIRST_NAME, WORKER.LAST_NAME, DESIGNATION.TITLE, TITLE.AFFECTED_FROM FROM WORKER, DESIGNATION, TITLE WHERE TITLE.DESIGNATION_ID = DESIGNATION.ID and TITLE.WORKER_REF_ID = WORKER.WORKER_ID AND TITLE.AFFECTED_FROM IN (SELECT TOP 1 TITLE.AFFECTED_FROM FROM TITLE  WHERE TITLE.WORKER_REF_ID = WORKER.WORKER_ID ORDER BY TITLE.AFFECTED_FROM DESC) ORDER BY FIRST_NAME 
/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/
go

SET NOCOUNT ON;


SELECT DEPARTMENT.DEPT_NAME FROM DEPARTMENT WHERE DEPARTMENT.ID NOT IN (SELECT WORKER.DEPT_ID FROM WORKER WHERE WORKER.DEPT_ID IS NOT NULL)
/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/
go

SET NOCOUNT ON;

SELECT DISTINCT F_WORKER.FIRST_NAME, F_WORKER.LAST_NAME, DATEFROMPARTS(DATEPART(YEAR, F_WORKER.JOINING_DATE), DATEPART(month, F_WORKER.JOINING_DATE), DATEPART(DAY, F_WORKER.JOINING_DATE))FROM WORKER as F_WORKER INNER JOIN WORKER AS S_WORKER ON DATEFROMPARTS(DATEPART(YEAR, F_WORKER.JOINING_DATE), DATEPART(month, F_WORKER.JOINING_DATE), DATEPART(DAY, F_WORKER.JOINING_DATE)) = DATEFROMPARTS(DATEPART(YEAR, S_WORKER.JOINING_DATE), DATEPART(month, S_WORKER.JOINING_DATE), DATEPART(DAY, S_WORKER.JOINING_DATE)) WHERE F_WORKER.WORKER_ID != S_WORKER.WORKER_ID
/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/

go

SET NOCOUNT ON;

SELECT WORKER.FIRST_NAME, WORKER.LAST_NAME, WORKER.JOINING_DATE FROM WORKER WHERE WORKER.WORKER_ID NOT IN (SELECT BONUS.WORKER_REF_ID FROM BONUS) ORDER BY WORKER.FIRST_NAME
/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/

go

SET NOCOUNT ON;


-- SELECT AVG(WORKER.SALARY) AS A FROM WORKER
SELECT M_WORKER.FIRST_NAME, M_WORKER.LAST_NAME, DEPARTMENT.DEPT_NAME, M_WORKER.SALARY FROM WORKER M_WORKER INNER JOIN DEPARTMENT ON M_WORKER.DEPT_ID = DEPARTMENT.ID WHERE M_WORKER.SALARY > (SELECT AVG(L_WORKER.SALARY) FROM WORKER L_WORKER WHERE M_WORKER.DEPT_ID =  L_WORKER.DEPT_ID)
/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/

go

SET NOCOUNT ON;

SELECT WORKER.FIRST_NAME, WORKER.LAST_NAME, COALESCE((SUM(BONUS.BONUS_AMOUNT)), 0) FROM WORKER LEFT OUTER JOIN BONUS ON WORKER.WORKER_ID = BONUS.WORKER_REF_ID GROUP BY WORKER.FIRST_NAME, WORKER.LAST_NAME ORDER BY SUM(BONUS.BONUS_AMOUNT) DESC
/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/

go

SET NOCOUNT ON;


-- COUNT(BONUS.WORKER_REF_ID)
SELECT WORKER.FIRST_NAME, DEPARTMENT.DEPT_NAME, DATEPART(YEAR, BONUS_DATE), COUNT(BONUS.BONUS_DATE) FROM WORKER, DEPARTMENT, BONUS WHERE DEPARTMENT.ID = WORKER.DEPT_ID AND WORKER.WORKER_ID = BONUS.WORKER_REF_ID GROUP BY WORKER.FIRST_NAME, DEPARTMENT.DEPT_NAME, BONUS_DATE having COUNT(BONUS.WORKER_REF_ID) > 1
/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/

go

SET NOCOUNT ON;

SELECT WORKER.FIRST_NAME, WORKER.LAST_NAME, DEPARTMENT.DEPT_NAME, WORKER.SALARY FROM WORKER, DEPARTMENT WHERE WORKER.DEPT_ID = DEPARTMENT.ID AND SALARY IN (SELECT DISTINCT TOP 2 WORKER.SALARY FROM WORKER ORDER BY SALARY DESC) AND SALARY < (SELECT DISTINCT TOP 1 WORKER.SALARY FROM WORKER ORDER BY SALARY DESC)
/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/

go

SET NOCOUNT ON;

SELECT WORKER.FIRST_NAME, WORKER.LAST_NAME, DEPARTMENT.DEPT_NAME, SUM(BONUS_AMOUNT) FROM WORKER, DEPARTMENT, BONUS WHERE WORKER.WORKER_ID IN (SELECT WORKER_REF_ID FROM BONUS WHERE DATEPART(YEAR, BONUS.BONUS_DATE) = 2017) AND WORKER.WORKER_ID NOT IN (SELECT WORKER_REF_ID FROM BONUS WHERE DATEPART(YEAR, BONUS.BONUS_DATE) = 2018) AND WORKER.DEPT_ID = DEPARTMENT.ID AND WORKER.WORKER_ID = BONUS.WORKER_REF_ID GROUP BY WORKER.FIRST_NAME, WORKER.LAST_NAME, DEPARTMENT.DEPT_NAME
/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/

go